# # Default Spring Profile
# server:
#   error:
#     include-message: always

# logging:
#   level:
#     root: INFO
#     com.cclean: DEBUG
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# ---
# # for docker

# spring:
#   datasource:
#     url: jdbc:mysql://database/ccleandb
#     username: user
#     password: pwd

#   jpa:
#     hibernate:
#       ddl-auto: none

#   config:
#     activate:
#       on-profile: docker

#   sql:
#     init:
#       platform: mysql
#       mode: always

# server.port: 8080

# spring.datasource.hikari.initializationFailTimeout: 60000










# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.cclean: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# For docker

spring:
  datasource:
    url: jdbc:mysql://database/ccleandb
    username: user
    password: pwd

  jpa:
    hibernate:
      ddl-auto: none

  config:
    activate:
      on-profile: docker

  sql:
    init:
      platform: mysql
      mode: always

server.port: 8080

spring.datasource.hikari.initializationFailTimeout: 60000

---
# For tests (H2 Database)

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
      INIT=RUNSCRIPT FROM 'classpath:h2_schema.sql'\\;RUNSCRIPT FROM 'classpath:h2_data.sql'
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

  config:
    activate:
      on-profile: test

server.port: 8080
