# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.cclean: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Thymeleaf Configuration (✅ Fix for template not found)
spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    cache: false  # Disable caching for development/testing
---
# for docker

spring:
  datasource:
    url: jdbc:mysql://database/ccleandb
    username: user
    password: pwd

  jpa:
    hibernate:
      ddl-auto: none

  config:
    activate:
      on-profile: docker

  sql:
    init:
      platform: mysql
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: viniciusvelozodesousa@gmail.com
    password: afbalomnaskqhzrm
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    audience: ${OKTA_OAUTH2_AUDIENCE}

server.port: 8080

spring.datasource.hikari.initializationFailTimeout: 60000