services:
  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ccleandb
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd 
    ports:
      - "3306:3306"
    volumes:
      - ./data/database:/var/lib/database
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../../../
      dockerfile: src/main/docker/Dockerfile
    container_name: cclean_backend
    ports:
      - "8080:8080"
    env_file:
      - ../../../.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - database

  frontend:
    build:
      context: ../../../
      dockerfile: cclean-frontend/Dockerfile
    container_name: cclean_frontend
    ports:
      - "5173:5173"
    env_file:
      - ../../../cclean-frontend/.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - database
    restart: always
    ports:
      - "8081:80"                        # Expose phpMyAdmin on port 8081
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - database # Ensure MySQL starts before phpMyAdmin

volumes:
  mysql_data:
