name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: cclean-frontend/package-lock.json
    - name: Install dependencies
      run: npm install
      working-directory: ./cclean-frontend
    - name: Run npm lint to ensure frontend code is linted
      run: npm run lint
      working-directory: ./cclean-frontend
    - name: Run build to ensure no build errors
      run: npm run build
      working-directory: ./cclean-frontend
