name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./cclean-frontend/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./cclean-frontend

    - name: Run lint checks
      run: npm run lint --max-warnings=0
      working-directory: ./cclean-frontend

    - name: Run TypeScript type checking
      run: npm run tsc
      working-directory: ./cclean-frontend

    - name: Run tests
      run: npm test
      working-directory: ./cclean-frontend

    - name: Build application
      run: npm run build
      working-directory: ./cclean-frontend
